name: Latest Repos

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update profile README with latest GitHub repos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "projects"
          max_post_count: 5
          feed_list: "https://github.com/Jaiswalmagic1?tab=repositories"
          custom_post_type: "github"
